### ISSUE TITLE
display issue on cellphone vertical mode

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#1]
the search bar was displayed as 2 line; 
the doctor table can not be completely display without moving to right;

**Comment by feiyunzhou** [comment]
The 1st issue has been resolved.
Regrading the 2nd issue:
It's not good idea to display so wide table on mobile.  Maybe one of solutions is that hiding some columns on mobile device dynamically

**Comment by tigerzhou** [comment]
agree with your idea on the 2nd issue

**Comment by feiyunzhou** [comment]
Resolved this problem by using FooTable(http://themergency.com/footable/), but css need adjust
