### ISSUE TITLE
add call history page under Account and doctor detailed page

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#10]
1.after clicking the details on the account table, navigate the account detailed page, add the call history of this hospital on the right side under doctor list;
1. add the doctor name navigate to doctor detail page, and show the call history on the right side of detailed page

**Comment by feiyunzhou** [comment]
Need more inputs about this feature

**Comment by tigerzhou** [comment]
are you coming to office tomorrow ? I will be in office afternoon

发自我的 iPhone

在 2013-6-2，下午11:03，feiyunzhou notifications@github.com 写道：
