### ISSUE TITLE
Some andriod mobile browser can not login to the system

### ISSUE THREAD

**Issue by alexsong54** [feiyunzhou/fei#136]

**Comment by feiyunzhou** [comment]
Sometimes I can't login into the system in my Mac book, I must click submission twice.  I saw these WARN in logs. Please help investigate it ASAP.  Priority 1 bug!!!

 WARN   [2013-10-25 00:49:16,265] [http-bio-8080-exec-1](AbstractTextComponent.java:170)
        Couldn't resolve model type of Model:classname=[org.apache.wicket.model.PropertyModel]:nestedModel=[]:expression=[username] for [TextField [Component id = username]], please set the type yourself.

 WARN   [2013-10-25 00:49:23,725] [http-bio-8080-exec-1](AbstractTextComponent.java:170)
        Couldn't resolve model type of Model:classname=[org.apache.wicket.model.PropertyModel]:nestedModel=[]:expression=[username] for [TextField [Component id = username]], please set the type yourself.
