### ISSUE TITLE
display different color for different activity type on calendar

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#15]
eg: 
Blue=> planned call
Red=> planned meeting
Yellow=> planned coaching

gray/blue => completed call
gray/red=> completed call
gray/yellow= completed coaching

Add legend for each type of activities, reference github labels

**Comment by feiyunzhou** [comment]
Lots of color here
http://www.computerhope.com/htmcolor.htm

**Comment by feiyunzhou** [comment]
completed in 5685f3a0cb2fcbcb33ca97ab6f760bf8a8e5db89
