### ISSUE TITLE
Calendar header font Size revise

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#2]
smaller calendar header font size 
and translate the English to Chinese

BTW, this is really good communicate channel for software updates

**Comment by feiyunzhou** [comment]
Yes.  It's being used as a tracker of bugs

**Comment by feiyunzhou** [comment]
please keep raising more issues, and your suggestion

**Comment by feiyunzhou** [comment]
Fixed by config some third-party js libs

**Comment by tigerzhou** [comment]
thanks a lot
