### ISSUE TITLE
add hyperlink to account name 

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#20]
navigation: 
1. Account tab
2. on account table, make the account name drill-able to see the account detailed page instead of "details" button

navigation: 
1. Doctors tab
2. on doctor table, the doctor name and account name are both drill-able

**Comment by feiyunzhou** [comment]
When the UI responsively running on the mobile phone, the default click event for the name is to expand the detailed information for the account/contact.  Due to this reason, I would like it keeps as current design. 

drilldownable  name not good for the responsive UI.
