### ISSUE TITLE
use more icon instead of words

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#21]
1. on doctor table, the last field is "create a Call", just use a icon, for instance use this icon http://www.iconarchive.com/show/junior-icons-by-treetog/user-group-icon.html
   http://www.iconarchive.com/show/onebit-icons-by-icojam/chat-icon.html
2. give a different color for segmentation "A", B, C, D

2 Give color to the call times field

**Comment by feiyunzhou** [comment]
Just for remindering
Need implement a component which uses to represent the data of contact table because there are at least two page display the contact information.
