### ISSUE TITLE
导入数据在执行导入之前进行转换编码方式的处理，或者直接将数据库编码改成GBK

### ISSUE THREAD

**Issue by alexsong54** [feiyunzhou/fei#267]

**Comment by alexsong54** [comment]
二师兄，这个问题很关键，因为下周我们给客户演示的时候第一个演示的就是导入功能，如果还是像现在这样操作很复杂，恐怕会达不到客户的要求

**Comment by feiyunzhou** [comment]
fixed in 776a23b965bca3c17944383c206d7a971a7f0d63
