### ISSUE TITLE
account and Doctor drill down to details page, and see the call history

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#3]
can we make the account and doctor drill-able to see the call history, and also a report chart for the call achievement rate..., 

and add "Call"button on doctor detailed page navigate to call creation page
Thanks

**Comment by feiyunzhou** [comment]
completed ""Call"button on doctor detailed page navigate to call creation page"
commit id: c748017ba72dc5f9921395c635988478208ef2c2

**Comment by feiyunzhou** [comment]
use this lib to implement the chart
https://github.com/mbostock/d3/wiki/Gallery
