### ISSUE TITLE
contact and edetailing doesnt support offline

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#30]

**Comment by feiyunzhou** [comment]
long time ago, we planed to not support offline for the offline version so now we have to change it again

**Comment by DongJingChao** [comment]
飞云哥

##      when I was browsing the http://localhost:8080/crm . it always prompts the page was not found and mysql -ucrm < tigerp/crm/src/main/db/dump.sql' aluays propmpt paht was not found. 

I will go on

------------------ 原始邮件 ------------------
发件人: "feiyunzhou"notifications@github.com;
发送时间: 2013年8月27日(星期二) 上午7:03
收件人: "feiyunzhou/tigerp"tigerp@noreply.github.com; 

主题: Re: [tigerp] contact and edetailing doesnt support offline (#30)

long time ago, we planed to not support offline for the offline version so now we have to change it again
