### ISSUE TITLE
call page can not be edit when drill from calendar

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#45]

**Comment by feiyunzhou** [comment]
give more specific steps?
在 2013-9-25 PM2:04，"tigerzhou" notifications@github.com写道：

**Comment by tigerzhou** [comment]
there is only back and submit button, not edit

**Comment by feiyunzhou** [comment]
clear your browser's history information, and try it again
在 2013-9-25 PM2:12，"tigerzhou" notifications@github.com写道：
