### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#5]
the search doesnt work after footable

**Comment by feiyunzhou** [comment]
you need input at least two words

**Comment by tigerzhou** [comment]
那A,b,分级如何处理

发自我的 iPhone

在 2013-5-24，上午10:15，feiyunzhou notifications@github.com 写道：

**Comment by feiyunzhou** [comment]
Can't work so far for this type of word

On Fri, May 24, 2013 at 10:33 AM, tigerzhou notifications@github.comwrote:

> 那A,b,分级如何处理
> 
> 发自我的 iPhone
> 
> 在 2013-5-24，上午10:15，feiyunzhou notifications@github.com 写道：
> 
> > you need input at least two words
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/feiyunzhou/tigerp/issues/5#issuecomment-18383660
> .

## 

Feiyun Zhou  周飞云

**Comment by feiyunzhou** [comment]
There is a workaround:  Type  'A[space]'

**Comment by feiyunzhou** [comment]
The filter is configurable so the issue fixed
commit id: 25ea245c7a3d46aea1573253b5fdbe9b05d88792
