### ISSUE TITLE
Add more field to Call and Meeting

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#6]
Add the following field to a call:

Call objective
Call summary
Product: 

Add the following button on call layout 
Launch e-detailing: once click it this, navigate to 展示page, and add rating to the page

**Comment by feiyunzhou** [comment]
For what? offline or online?

**Comment by tigerzhou** [comment]
offline

发自我的 iPhone

在 2013-5-24，下午11:32，feiyunzhou notifications@github.com 写道：

**Comment by tigerzhou** [comment]
Next week I would demo to customer to show our mobile/html5 capabilities;  and also consulting knowledge;  so we would make it more industry focus; will request more functions later

**Comment by feiyunzhou** [comment]
Give more specific description about this feature? a little bit confused. Thanks

**Comment by feiyunzhou** [comment]
duplicated Issue #7
