### ISSUE TITLE
关于权限控制

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#67]
当系统管理员新建了一个医院后，并将这个医院给了某个代表，那么这个代表就可以看到这个医院下全部的医生，这个ok；但这些医生不全都显示在他的医生下面，得到医院下进行查看

当将代表加入到一个医生的团队，那么这个代表可以看到这个医生，而且通过点击医生的id，可以查看医院的信息，但这个医院信息不能在医院列表中显示；

**Comment by feiyunzhou** [comment]
给了医生，同时把医院的关系添加进去
