### ISSUE TITLE
calendar editable

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#7]
Can edit existing activities, 
Can view existing activities

**Comment by feiyunzhou** [comment]
1. When click the activity, will open a new page(editor) where we can vide/edit the selected activity. 
2. Add a button in the editor. When click it, forward to a new page for the presentation.

**Comment by feiyunzhou** [comment]
Fixed in 390a674d0885bb2d0076aa0622ce5aaed271a334
