### ISSUE TITLE
Add call frequency and coverage to doctors model

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#8]
when a sales does a call planning, he/she need to reference the call frequency : for instance: 4 times/Month;

And another filed is called coverage, that means how many times the doctor be called since this month;

you could use some icon to describe the current status, start, ball,(Red/yellow/green)...

**Comment by feiyunzhou** [comment]
Will add 3 fields in doctor table:
级别:  
拜访目标:   The number of visit's targeting which is decided by '级别'
拜访次数： The number of times of visiting to the doctor.

**Comment by tigerzhou** [comment]
it is working on doctor table, but there is no active call # field on doctor list under account

**Comment by feiyunzhou** [comment]
a known issue

**Comment by feiyunzhou** [comment]
Fixed in 390a674d0885bb2d0076aa0622ce5aaed271a334
