### ISSUE TITLE
管理员重置密码功能

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#85]

**Comment by Brendacui** [comment]
9ad7d1fa2fc479ea194cfc98fd6c117816851a4a,此功能已添加完成！

**Comment by tigerzhou** [comment]
不可用

**Comment by Brendacui** [comment]
管理员重置密码是可以使用的，重置后的密码为123456.

**Comment by tigerzhou** [comment]
你这种重置方法是不对的，另外coaching的bug搞好了吗。

Brendacui notifications@github.com编写：

> 管理员重置密码是可以使用的，重置后的密码为123456.ReplytothisemaildirectlyorviewitonGitHub.
