### ISSUE TITLE
销售代表没有了创建医生的权限

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#92]
销售代表应该有创建医生的权限；
且当系统管理员给销售代表添加了医生，那么这个医生所在的医院，销售代表应该也有权限查看，但在医院列表中不没有显示，在用户下面的医院列表中也没有显示

**Comment by feiyunzhou** [comment]
fixed in 4053f356bd40530ea66707771ddff07016aca4d3
