### ISSUE TITLE
汇报对象，一旦选择后，不可以清空

### ISSUE THREAD

**Issue by tigerzhou** [feiyunzhou/fei#96]

**Comment by feiyunzhou** [comment]
为什么不能清空？

**Comment by tigerzhou** [comment]
不知道如何操作来清空

feiyunzhou notifications@github.com编写：

> 为什么不能清空？ReplytothisemaildirectlyorviewitonGitHub.

**Comment by DongJingChao** [comment]
该字段现在为readonly，如果去掉该控制，用户选择上级经理后再手动修改字段会造成数据错误的BUG

**Comment by DongJingChao** [comment]
存入的数据可能是不存在的经理

**Comment by feiyunzhou** [comment]
现在用户可以从查询列表中选“无”来清空

**Comment by feiyunzhou** [comment]
fixed in 1f1b897cf766400a0182319df8f65966a4e9b0b4
